添加drv_imu_inv驱动，文档，移植，删除旧drv_imu_inv
CkovMk/HITSIC_Module pull request #20
Opened 2020-10-16 07:51 UTC by beforelight

2020-10-16 07:54 UTC, CkovMk commented on utilities/drv_imu_invensense_def.hpp
> +#define REMOTEIIC_DRV_IMU_INVENSENSE_DEF_HPP
把无关定义删掉吧

2020-10-16 08:07 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +#define INV_NO_DEBUG  //关闭代码调试输出，默认打开
建议支持由宏定义控制打印不同的调试级别 格式为：[X] IMU_INV.9250 : message
具体可查看“app_menu_def.hpp”中有关日志打印的实现

2020-10-16 08:07 UTC, CkovMk commented on d_default/drv_imu_invensense_port.hpp
> +                             const unsigned char *val, unsigned int len) {
使用"cstdint"头文件，
unsigned char -> uint8_t

2020-10-16 08:07 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +#define INV_NO_DEBUG  //关闭代码调试输出，默认打开
所有这些控制宏，都应该在port文件中定义，且采用`#if (defined(YOUR_MACRO) && (YOUR_MACRO >0))`
的形式

2020-10-16 11:31 UTC, CkovMk commented on d_default/drv_imu_invensense_port.hpp
> +#define INV_NO_DEBUG 1
改成#define HITSIC_IMU_INV_xxx

2020-10-16 11:31 UTC, CkovMk commented on d_default/drv_imu_invensense_port.hpp
>                    readNonBlocking(_readNonBlocking), writeNonBlocking(_writeNonBlocking) {}
接口应该改成直接实例化一个类，而不是写四个函数填充已有的函数指针。
建议：i2c接口类内包含四个静态接口函数，由用户实现。i2c接口类作为类型模板传入。当存在多个实例时，用户需要实现多个i2c接口类。

2020-10-16 11:31 UTC, CkovMk commented on utilities/drv_imu_invensense.hpp
> +#define DRV_IMU_INVENSENSE_HPP
改为UTILITIES_DRV_IMU_INVENSENSE_HPP

2020-10-16 11:31 UTC, CkovMk commented on d_default/drv_imu_invensense_port.hpp
> +#define DRV_IMU_INVENSENSE_PORT_HPP
改为D_DEFAULT_DRV_IMU_INVENSENSE_PORT_HPP

2020-10-16 11:31 UTC, CkovMk commented on utilities/drv_imu_invensense.hpp
>           * @return {int}             : 错误码
含义是什么，不需要接收数据时置为nullptr，写清楚

2020-10-16 11:31 UTC, CkovMk commented on utilities/drv_imu_invensense_def.hpp
> +#define DRV_IMU_INVENSENSE_DEF_HPP
加UTILITIES_

2020-10-16 12:14 UTC, beforelight commented on d_default/drv_imu_invensense_port.hpp
> +#endif//(defined(INV_IMU_DEBUG)&&(INV_IMU_DEBUG>0))
不行，这样关于log接口就没法修改了，本体当中log并不是调用的printf

2020-10-16 12:17 UTC, beforelight commented on d_default/drv_imu_invensense_port.hpp
>                    readNonBlocking(_readNonBlocking), writeNonBlocking(_writeNonBlocking) {}
使用类模板一旦出错无法定位，这样还不如留个类声明，由用户去实现

2020-10-17 15:11 UTC, CkovMk requested changes

2020-10-17 15:11 UTC, CkovMk commented on d_default/drv_imu_invensense_port.hpp
> +}
这部分合并到设备类里

2020-10-19 10:16 UTC, CkovMk approved these changes

2020-10-19 10:16 UTC, merged