补全文档，修复虚函数重载后继承的问题
CkovMk/HITSIC_Module pull request #28
Opened 2020-10-20 12:50 UTC by beforelight

2020-10-20 13:05 UTC, beforelight commented
#29

2020-10-20 16:35 UTC, CkovMk commented on doc/drv_imu_invensense.md
>  - 本驱动重构了在k66工程上的c语言版本的imu驱动，同样支持了3款mpu6050,mpu9250,icm20602，把i2c作为主要接口，并且添加了自检函数，增加使用的可靠性。
注意一下大小写 MPU6050 ICM20602

2020-10-20 16:44 UTC, CkovMk requested changes

2020-10-20 16:44 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +##### 不确定使用的imu型号
IMU

2020-10-20 16:44 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +5. 调用`ReadSensorBlocking()`方法读取传感器数据并调用`Converter()`方法转换数据，或者，调用`ReadSensorNonBlocking()` 方法，等待数据传输完成之后再调用`Converter()`方法转换数据。
API名称应该以动作命名：使用Convert，不要用Converter

2020-10-20 16:44 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +inv::i2cInterface_t my_i2c(&iic, remote_i2c_read, remote_i2c_write);
咋又出来一个`iic`？

2020-10-20 16:44 UTC, CkovMk commented on doc/drv_imu_invensense.md
> +                usleep(10000);//等待10ms
给这玩意创建个接口吧

2020-10-20 16:46 UTC, beforelight commented on doc/drv_imu_invensense.md
> +5. 调用`ReadSensorBlocking()`方法读取传感器数据并调用`Converter()`方法转换数据，或者，调用`ReadSensorNonBlocking()` 方法，等待数据传输完成之后再调用`Converter()`方法转换数据。
这已经改不动了

2020-10-20 16:48 UTC, beforelight commented on doc/drv_imu_invensense.md
> +inv::i2cInterface_t my_i2c(&iic, remote_i2c_read, remote_i2c_write);
测试平台的I2C类

2020-10-20 16:49 UTC, beforelight commented on doc/drv_imu_invensense.md
> +                usleep(10000);//等待10ms
不可能延时api都由我来创建吧

2020-10-21 15:57 UTC, CkovMk approved these changes

2020-10-21 15:58 UTC, merged